### ISSUE TITLE
getOneOfs() oneofs cardinality not known!

### ISSUE THREAD

**Issue by Nankys** [hyperweb-io/telescope#643]
Error: getOneOfs() oneofs cardinality not known!
    at getOneOfs (/root/gencode/node_modules/.pnpm/@cosmology+ast@1.8.1/node_modules/@cosmology/ast/main/encoding/proto/types.js:162:15)
    at createProtoType (/root/gencode/node_modules/.pnpm/@cosmology+ast@1.8.1/node_modules/@cosmology/ast/main/encoding/proto/interface/proto.js:59:42)
    at buildBaseTypeScriptInterface (/root/gencode/node_modules/.pnpm/@cosmology+telescope@1.8.3/node_modules/@cosmology/telescope/main/build.js:41:49)
    at /root/gencode/node_modules/.pnpm/@cosmology+telescope@1.8.3/node_modules/@cosmology/telescope/main/build.js:118:58
    at Array.forEach (<anonymous>)
    at TelescopeParseContext.buildBase (/root/gencode/node_modules/.pnpm/@cosmology+telescope@1.8.3/node_modules/@cosmology/telescope/main/build.js:115:20)
    at /root/gencode/node_modules/.pnpm/@cosmology+telescope@1.8.3/node_modules/@cosmology/telescope/main/generators/create-types.js:46:17
    at Array.map (<anonymous>)
    at plugin (/root/gencode/node_modules/.pnpm/@cosmology+telescope@1.8.3/node_modules/@cosmology/telescope/main/generators/create-types.js:43:35)
    at /root/gencode/node_modules/.pnpm/@cosmology+telescope@1.8.3/node_modules/@cosmology/telescope/main/builder.js:106:39

https://github.com/sunriselayer/sunrise/tree/main/proto/sunrise
https://github.com/sunriselayer/sunrise/blob/effea572e0b2661fca71a8bb88b8af530681ae57/proto/sunrise/swap/route.proto#L40
https://github.com/sunriselayer/sunrise/blob/effea572e0b2661fca71a8bb88b8af530681ae57/proto/sunrise/swap/metadata.proto#L51
https://github.com/sunriselayer/sunrise/blob/effea572e0b2661fca71a8bb88b8af530681ae57/proto/sunrise/swap/in_flight_packet.proto#L39
https://github.com/sunriselayer/sunrise/blob/effea572e0b2661fca71a8bb88b8af530681ae57/proto/sunrise/swap/in_flight_packet.proto#L43

**Comment by Nankys** [comment]
https://github.com/sunriselayer/sunrise/tree/main/proto/sunrise

**Comment by Zetazzz** [comment]
Hi, thanks for the feedback!

I think we can improve the error msg to make it more clear.

About this issue, I believe there maybe a message which has multiple oneofs like:


message TestRequest {

  uint32 test_num = 1;
  

  oneof test_oneof {
    string id = 2;
    string name = 3;
  }
  oneof test_oneof1 {
    string id = 4;
    string name = 5;
  }
}

If there's a place like this, they have to combine into one.

**Comment by Zetazzz** [comment]
message IncomingInFlightPacket {
  PacketIndex index = 1 [
    (gogoproto.nullable)   = false,
    (amino.dont_omitempty) = true
  ];
  bytes data = 2;
  string src_port_id = 3;
  string src_channel_id = 4;
  string timeout_height = 5;
  uint64 timeout_timestamp = 6;
  bytes ack = 7;
  RouteResult result = 8 [
    (gogoproto.nullable)   = false,
    (amino.dont_omitempty) = true
  ];
  string interface_fee = 9 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  oneof change {
    PacketIndex outgoing_index_change = 10;
    bytes ack_change = 11;
  }
  oneof forward {
    PacketIndex outgoing_index_forward = 12;
    bytes ack_forward = 13;
  }
}

**Comment by NorOldBurden** [comment]
For any further questions, please open another issue
